//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_Indicador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPandora_Indicador()
        {
            this.NewPandora_IndicadorRegistro = new HashSet<NewPandora_IndicadorRegistro>();
        }
    
        public int IdIndicador { get; set; }
        public Nullable<int> IdExperimento { get; set; }
        public string Indicador { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> FlagMostrar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPandora_IndicadorRegistro> NewPandora_IndicadorRegistro { get; set; }
        public virtual NewPandora_Experimento NewPandora_Experimento { get; set; }
    }
}
