//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_Interaccion_Usuario
    {
        public int Id { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> IDOpcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
