//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_RolOpcion
    {
        public int IdRolOpcion { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdOpcion { get; set; }
    
        public virtual NewPandora_Opcion NewPandora_Opcion { get; set; }
        public virtual NewPandora_Rol NewPandora_Rol { get; set; }
    }
}
