//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_IndicadorRegistro
    {
        public int IdIndicadorRegistro { get; set; }
        public Nullable<int> IdIndicador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public string Guid { get; set; }
    
        public virtual NewPandora_Indicador NewPandora_Indicador { get; set; }
    }
}
