//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReinventaDatosCampaniaRegistro
    {
        public int IdRegistro { get; set; }
        public Nullable<int> IdCampania { get; set; }
        public string DocumentoIdentidad { get; set; }
        public string NombresApellidos { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> CheckProteccionDatos { get; set; }
    
        public virtual ReinventaDatosCampania ReinventaDatosCampania { get; set; }
    }
}
