//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_mAGENDACOMERCIAL_CLIENTE
    {
        public int CODIGOCLIENTE { get; set; }
        public string RUC { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string DIRECCION { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public string ZONA { get; set; }
        public string GIRO_NEGOCIO { get; set; }
        public string GRUPO_ECONOMICO { get; set; }
        public string SEGMENTO { get; set; }
        public string SCORE { get; set; }
        public string CROSS_CLIENTE { get; set; }
        public string FACTURACION { get; set; }
        public string ROE { get; set; }
        public string SOW { get; set; }
        public string RENTABILIDAD { get; set; }
        public string VOLUMEN_NEGOCIO { get; set; }
        public string VOLUMEN_PASIVOS { get; set; }
        public string VOLUMEN_ACTIVOS { get; set; }
        public string VOLUMEN_CONTINGENTES { get; set; }
        public string CALIFICACION_BANBIF { get; set; }
        public string CALIFICACION_SSFF { get; set; }
        public string SISTEMA_VIGILANCIA { get; set; }
        public string LINEA_DISPONIBLE { get; set; }
        public string DEUDA_RCC { get; set; }
    }
}
