//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA.ModelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_mAGENDACOMERCIAL_CLIENTE_CONTACTO_COMENTARIOS
    {
        public int CODIGOCOMENTARIO { get; set; }
        public Nullable<int> CODIGOCONTACTO { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual TBL_mAGENDACOMERCIAL_CLIENTE_CONTACTO TBL_mAGENDACOMERCIAL_CLIENTE_CONTACTO { get; set; }
    }
}
