//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NewPandora_Experimento> NewPandora_Experimento { get; set; }
        public virtual DbSet<NewPandora_ExperimentoOpcion> NewPandora_ExperimentoOpcion { get; set; }
        public virtual DbSet<NewPandora_Opcion> NewPandora_Opcion { get; set; }
        public virtual DbSet<NewPandora_Rol> NewPandora_Rol { get; set; }
        public virtual DbSet<NewPandora_RolOpcion> NewPandora_RolOpcion { get; set; }
        public virtual DbSet<NewPandora_StatusExperimento> NewPandora_StatusExperimento { get; set; }
        public virtual DbSet<NewPandora_Usuario> NewPandora_Usuario { get; set; }
        public virtual DbSet<ReinventaDatosCampania> ReinventaDatosCampania { get; set; }
        public virtual DbSet<ReinventaDatosCampaniaCarrusel> ReinventaDatosCampaniaCarrusel { get; set; }
        public virtual DbSet<ReinventaDatosCampaniaRegistro> ReinventaDatosCampaniaRegistro { get; set; }
        public virtual DbSet<NewPandora_PropuestaExperimento> NewPandora_PropuestaExperimento { get; set; }
    }
}
