//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_StatusExperimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPandora_StatusExperimento()
        {
            this.NewPandora_Experimento = new HashSet<NewPandora_Experimento>();
            this.NewPandora_PropuestaExperimento = new HashSet<NewPandora_PropuestaExperimento>();
        }
    
        public int IdStatusExperimento { get; set; }
        public string Status { get; set; }
        public Nullable<bool> FlagExperimento { get; set; }
        public Nullable<int> Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPandora_Experimento> NewPandora_Experimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPandora_PropuestaExperimento> NewPandora_PropuestaExperimento { get; set; }
    }
}
