//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_Experimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPandora_Experimento()
        {
            this.NewPandora_ExperimentoOpcion = new HashSet<NewPandora_ExperimentoOpcion>();
        }
    
        public int IdExperimento { get; set; }
        public string NombreExperimento { get; set; }
        public string Descripcion { get; set; }
        public string Tecnologia { get; set; }
        public string DesarrolladoPor { get; set; }
        public Nullable<int> Indicador { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Url { get; set; }
        public Nullable<int> IdUsuarioContacto { get; set; }
        public Nullable<bool> FlagPublico { get; set; }
        public Nullable<int> IdStatusExperimento { get; set; }
    
        public virtual NewPandora_StatusExperimento NewPandora_StatusExperimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPandora_ExperimentoOpcion> NewPandora_ExperimentoOpcion { get; set; }
    }
}
