//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Nuevo.Pandora.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPandora_Opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPandora_Opcion()
        {
            this.NewPandora_ExperimentoOpcion = new HashSet<NewPandora_ExperimentoOpcion>();
            this.NewPandora_RolOpcion = new HashSet<NewPandora_RolOpcion>();
        }
    
        public int IdOpcion { get; set; }
        public string NombreOpcion { get; set; }
        public string Url { get; set; }
        public Nullable<bool> FlagEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPandora_ExperimentoOpcion> NewPandora_ExperimentoOpcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPandora_RolOpcion> NewPandora_RolOpcion { get; set; }
    }
}
